---
- yum:
    name: "{{ item }}"
  with_items:
    - mod_ssl
    - git
    - sqlite-devel
    - curl-devel
    - httpd-devel
    - apr-devel
    - apr-util-devel

- git:
    repo: "{{ casino_repo }}"
    dest: "{{ casino_dir }}"
    version: "{{ casino_version }}"

# http://casino.rbcas.com/docs/installation/
# ansible can't install gems for some reason
- shell: chdir="{{ casino_dir}}" gem install "{{ item }}"
  with_items:
    - passenger
    - bundler

- shell: chdir="{{ casino_dir }}" creates="{{ casino_dir }}/db/production.sqlite3" ./script/install sqlite

- lineinfile:
    dest: "{{ casino_dir }}/db/production.sqlite3"
    regexp: "^(\s+timeout:).*"
    backrefs: yes
    line: "\1 120000"
    backup: yes

- lineinfile:
    dest: "{{ casino_dir }}/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/connection_adapters/sqlite_adapter.rb"
    regexp: "(.*@connection\.transaction)(\s.*)"
    backrefs: yes
    line: "\1(:immediate)\2"
    backup: yes

- shell: chdir="{{ casino_dir }}" bundle exec whenever --update-crontab CASino
  environment:
    RAILS_ENV: production
# " annoying vim syntax highlighting bug

- name: compiling assets
  shell: chdir="{{ casino_dir }}" bundle exec rake assets:precompile
  environment:
    RAILS_ENV: production
# " annoying vim syntax highlighting bug

- name: get passenger dir
  shell: passenger-install-apache2-module --snippet | grep PassengerRoot | cut -d ' ' -f 4
  register: passenger_dir

# the passenger conf must be away before the eventual compiling
- file:
    path: /etc/httpd/conf.d/passenger.conf
    state: absent


# if you kill ansible-playbook during passenger compilation, you might want to
#
# rm -rf /usr/local/ruby-1.9.3-p484/lib/ruby/gems/1.9.1/gems/passenger-4.0.53/buildout /etc/httpd/conf.d/passenger.conf /tmp/passenger_addon.*
# semodule -r passenger_addon
#
# or rm -rf {{ passenger_dir.stdout }}/buildout/
#
- name: compile apache2 passenger module
  shell: creates="{{ passenger_dir.stdout }}/buildout/apache2/mod_passenger.so" passenger-install-apache2-module -a

- file:
    path: /etc/httpd/conf.d/ssl.conf
    state: absent
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version != '6'
  notify: restart httpd

- stat:
    path: "{{ passenger_dir.stdout }}/buildout/apache2/mod_passenger.so"
  register: passenger_module

- assert:
    that:
      - passenger_module.stat.exists and passenger_module.stat.isreg

- shell: passenger-install-apache2-module --snippet > /etc/httpd/conf.d/passenger.conf
  notify: restart httpd

- copy:
    src: ssl.conf
    dest: /etc/httpd/conf.d/ssl.conf
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- lineinfile:
    backup: yes
    dest: "{{ '/etc/httpd/conf/httpd.conf' if ansible_os_family == 'RedHat' else '/etc/apache2/ports.conf' }}"
    insertafter: EOF
    line: "Listen {{ item }}"
  with_items:
    - 0.0.0.0:80
    - "0.0.0.0:{{ casino_port }}"
  notify: restart httpd

- template:
    src: casino.vhost.conf
    dest: /etc/httpd/conf.d/casino.vhost.conf
  notify: restart httpd

- template:
    src: cas.ldap.yml
    dest: /tmp/cas.ldap.yml

- name: configure log rotation for casino
  template: src=casino.logrotate dest=/etc/logrotate.d/casino owner=root group=root mode=0644

- shell: cat {{ casino_dir }}/config/cas.yml.example /tmp/cas.ldap.yml > {{ casino_dir }}/config/cas.yml
  notify: restart httpd

- file:
    path: "{{ casino_dir }}"
    owner: apache
    group: apache
    recurse: yes
  notify: restart httpd
