---
- yum:
    name: "{{ item }}"
  with_items:
    - mod_ssl
    - git
    - sqlite-devel
    - curl-devel
    - httpd-devel
    - apr-devel
    - apr-util-devel

- git:
    repo: "{{ casino_repo }}"
    dest: "{{ casino_dir }}"
    depth: 1


# http://casino.rbcas.com/docs/installation/
# ansible can't install gems for some reason
- shell: chdir="{{ casino_dir}}" gem install "{{ item }}"
  with_items:
    - passenger
    - bundler

- shell: chdir="{{ casino_dir }}" creates="{{ casino_dir }}/db/production.sqlite3" ./script/install sqlite

- shell: chdir="{{ casino_dir }}" bundle exec whenever --update-crontab CASino

- name: compiling assets
  shell: chdir="{{ casino_dir }}" bundle exec rake assets:precompile

- name: get passenger dir
  shell: passenger-install-apache2-module --snippet | grep PassengerRoot | cut -d ' ' -f 4
  register: passenger_dir

# if you kill ansible-playbook during passenger compilation, you might want to
# rm -rf {{ passenger_dir.stdout }}/buildout/
- name: compile apache2 passenger module
  shell: creates="{{ passenger_dir.stdout }}/buildout/apache2/mod_passenger.so" passenger-install-apache2-module -a

- shell: passenger-install-apache2-module --snippet > /etc/httpd/conf.d/passenger.conf
  notify: restart httpd

- copy:
    src: ssl.conf
    dest: /etc/httpd/conf.d/ssl.conf

- template:
    src: casino.vhost.conf
    dest: /etc/httpd/conf.d/casino.vhost.conf
  notify: restart httpd

- shell: "semodule -l | grep -q passenger_addon"
  register: passenger_addon_loaded
  ignore_errors: True

- template:
    src: cas.yml
    dest: "{{ casino_dir }}/config/cas.yml"
  notify: restart httpd

- file:
    path: "{{ casino_dir }}"
    owner: apache
    group: apache
    recurse: yes
  notify: restart httpd

- include: selinux.yml
  when: passenger_addon_loaded|failed
  notify: restart httpd
